name: asyn

# Trigger on pushes and PRs to any branch
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:

env:
  SETUP_PATH: .ci-local:.ci

jobs:
  test:
    name: ${{ matrix.os }}/${{ matrix.deps }}/${{ matrix.base }}/${{ matrix.cmp }}/${{ matrix.configuration }}/${{ matrix.cross }}
    runs-on: ${{ matrix.os }}
    env:
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      BASE: ${{ matrix.base }}
      SET: ${{ matrix.deps }}
      CI_CROSS_TARGETS: ${{ matrix.cross }}
      TEST: ${{ matrix.test }}
      APT: re2c
      CHOCO: re2c
      BREW: re2c

    strategy:
      fail-fast: false
      matrix:
        # Job names also name artifacts, character limitations apply
        include:
          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            deps: "deps2"

          - os: ubuntu-latest
            cmp: gcc
            configuration: static
            base: "7.0"
            deps: "deps2"

          - os: ubuntu-latest
            cmp: gcc
            configuration: static
            base: "7.0"
            deps: "deps2"

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "3.15"
            deps: "no-deps"

          - os: ubuntu-latest
            cmp: gcc
            configuration: static
            base: "3.15"
            deps: "deps2"

#          - os: ubuntu-latest
#            cmp: gcc
#            configuration: static
#            base: "3.14"
#            deps: "deps1"

          - os: windows-2019
            cmp: vs2019
            configuration: default
            base: "7.0"
            deps: "deps2"

          - os: windows-2019
            cmp: vs2019
            configuration: static
            base: "7.0"
            deps: "deps2"

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            deps: "no-deps"
            cross: "RTEMS-pc386-qemu@4.9"

          - os: ubuntu-latest
            cmp: gcc
            configuration: default
            base: "7.0"
            deps: "no-deps"
            cross: "RTEMS-pc386-qemu@4.10"
            test: NO

#          - os: ubuntu-latest
#            cmp: gcc
#            configuration: default
#            base: "7.0"
#            deps: "no-deps"
#            cross: "RTEMS-pc686-qemu@5"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare and compile EPICS dependencies
      run: python .ci/cue.py prepare

    - name: TIRPC
      run: echo TIRPC=YES > configure/CONFIG_SITE.Common.linux-x86_64

    - name: Build main module
      run: python .ci/cue.py build

    - name: Run main module tests
      run: python .ci/cue.py -T 20M test

    - name: Upload tapfiles Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: tapfiles ${{ matrix.name }}
        path: '**/O.*/*.tap'
        if-no-files-found: ignore

    - name: Collect and show test results
      if: ${{ always() }}
      run: python .ci/cue.py -T 5M test-results
